spring:
  datasource:
   url: jdbc:sqlserver://employeeazuresql.database.windows.net:1433;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
   username: m1088994mahesh
   password: Nidhitai@123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect :  org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 8083
    